driver:
  name: vagrant
  require_chef_omnibus: '12.13.37'

provisioner:
  name: chef_zero
  retry_on_exit_code:
    - 213
  max_retries: 1
  wait_for_retry: 1
  client_rb:
    exit_status: :enabled
    client_fork: false

verifier:
  name: inspec

platforms:
  - name: centos-6.9
  - name: centos-7.3
  - name: debian-7.11
  - name: debian-8.7
  - name: freebsd-10.3
  - name: freebsd-11.0
  - name: fedora-25
  - name: opensuse-leap-42.2
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: windows-2008r2
    driver:
      box: chef/windows-server-2008r2-standard # private box in Chef's Atlas account
  - name: windows-2012r2
    driver:
      box: chef/windows-server-2012r2-standard # private box in Chef's Atlas account
  - name: macosx-10.11
    driver:
      box: chef/macosx-10.11 # private box in Chef's Atlas account
      provider: vmware_fusion
  - name: sles-12-sp1
    driver:
      box: chef/sles-12-sp1-x86_64 # private box in Chef's Atlas account

suites:
  - name: default
    run_list:
      - recipe[test::default]
  - name: kill
    run_list:
      - recipe[test::kill]
  - name: direct_url
    run_list:
      - recipe[test::direct_url]
    includes: centos-6.9
  - name: constrained
    run_list:
      - recipe[test::constrained]
