driver:
  name: vagrant
  require_chef_omnibus: '<%= ENV["OMNIBUS_CHEF_VERSION"] || "12.13.37" %>'

provisioner:
  name: chef_solo
  retry_on_exit_code:
    - 213
  max_retries: 1
  wait_for_retry: 1
  solo_rb:
    exit_status: :enabled
    client_fork: false

verifier:
  name: inspec

platforms:
  - name: centos-6
  - name: centos-7
  - name: debian-8
  - name: debian-9
  - name: fedora-26
  - name: freebsd-10
  - name: freebsd-11
  - name: opensuse-leap-42
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: windows-2012r2
    driver:
      box: chef/windows-server-2012r2-standard # private box in Chef's Atlas account
    provisioner:
      wait_for_retry: 300
    transport:
      name: winrm
      elevated: true
  - name: windows-2016
    driver:
      box: chef/windows-server-2016-standard # private box in Chef's Atlas account
    provisioner:
      wait_for_retry: 300
    transport:
      name: winrm
      elevated: true
  - name: macosx-10.13
    driver:
      box: chef/macosx-10.13 # private box in Chef's Atlas account
      provider: vmware_fusion
  - name: sles-12-sp1
    driver:
      box: chef/sles-12-sp1-x86_64 # private box in Chef's Atlas account

suites:
  - name: default
    run_list:
      - recipe[test::default]
    excludes:
      - windows-2012r2
      - windows-2016
  - name: kill
    run_list:
      - recipe[test::kill]
    verifier:
      inspec_tests:
        - path: ./test/integration/default/
  - name: direct_url
    run_list:
      - recipe[test::direct_url]
    includes: centos-6
  - name: constrained
    run_list:
      - recipe[test::constrained]
    includes: centos-6
  - name: noop
    run_list:
      - recipe[test::noop]
    includes: centos-6
